name: 'shopify_source'
version: '0.7.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  shopify_source:
    +schema: stg_shopify
    +materialized: table
    tmp:
      +materialized: view
vars:
  shopify_source:
    customer_source: "{{ source('shopify','customer') }}"
    order_line_refund_source: "{{ source('shopify','order_line_refund') }}"
    order_line_source: "{{ source('shopify','order_line') }}"
    order_source: "{{ source('shopify','order') }}"
    product_source: "{{ source('shopify','product') }}"
    product_variant_source: "{{ source('shopify','product_variant') }}"
    transaction_source: "{{ source('shopify','transaction') }}"
    refund_source: "{{ source('shopify','refund') }}"
    order_adjustment_source: "{{ source('shopify','order_adjustment') }}"
    abandoned_checkout: "{{ source('shopify','abandoned_checkout') }}"
    collection_product: "{{ source('shopify','collection_product') }}"
    collection: "{{ source('shopify','collection') }}" 
    customer_tag: "{{ source('shopify','customer_tag') }}"
    discount_code: "{{ source('shopify','discount_code') }}"
    fulfillment: "{{ source('shopify','fulfillment') }}"
    inventory_item: "{{ source('shopify','inventory_item') }}"
    inventory_level: "{{ source('shopify','inventory_level') }}"
    location: "{{ source('shopify','location') }}"
    metafield: "{{ source('shopify','metafield') }}"
    order_note_attribute: "{{ source('shopify','order_note_attribute') }}"
    order_shipping_line: "{{ source('shopify','order_shipping_line') }}"
    order_shipping_tax_line: "{{ source('shopify','order_shipping_tax_line') }}"
    order_tag: "{{ source('shopify','order_tag') }}"
    order_url_tag: "{{ source('shopify','order_url_tag') }}"
    price_rule: "{{ source('shopify','price_rule') }}"
    product_image: "{{ source('shopify','product_image') }}"
    product_tag: "{{ source('shopify','product_tag') }}"
    shop: "{{ source('shopify','shop') }}" 
    tender_transaction: "{{ source('shopify','tender_transaction') }}"

    customer_pass_through_columns: []
    order_line_refund_pass_through_columns: []
    order_line_pass_through_columns: []
    order_pass_through_columns: []
    product_pass_through_columns: []
    product_variant_pass_through_columns: []
    transaction_pass_through_columns: []
    shopify__using_order_adjustment: true
    shopify__using_order_line_refund: true
    shopify__using_refund: true
