name: 'shopify_source_integration_tests'
version: '0.7.0'
profile: 'integration_tests'
config-version: 2

vars:
  shopify_schema: shopify_source_integration_tests
  shopify_source:
    customer_source:          "{{ ref('shopify_customer_data') }}"
    order_line_refund_source: "{{ ref('shopify_order_line_refund_data') }}"
    order_line_source:        "{{ ref('shopify_order_line_data') }}"
    order_source:             "{{ ref('shopify_order_data') }}"
    product_source:           "{{ ref('shopify_product_data') }}"
    order_adjustment_source:  "{{ ref('shopify_order_adjustment_data') }}"
    product_variant_source:   "{{ ref('shopify_product_variant_data') }}"
    refund_source:            "{{ ref('shopify_refund_data') }}"
    transaction_source:       "{{ ref('shopify_transaction_data') }}"

    abandoned_checkout_source: "{{ ref('shopify_abandoned_checkout_data') }}"
    collection_product_source: "{{ ref('shopify_collection_product_data') }}"
    collection_source: "{{ ref('shopify_collection_data') }}"
    customer_tag_source: "{{ ref('shopify_customer_tag_data') }}"
    discount_code_source: "{{ ref('shopify_discount_code_data') }}"
    fulfillment_source: "{{ ref('shopify_fulfillment_data') }}"
    inventory_item_source: "{{ ref('shopify_inventory_item_data') }}"
    inventory_level_source: "{{ ref('shopify_inventory_level_data') }}"
    location_source: "{{ ref('shopify_location_data') }}"
    metafield_source: "{{ ref('shopify_metafield_data') }}"
    order_note_attribute_source: "{{ ref('shopify_order_note_attribute_data') }}"
    order_shipping_line_source: "{{ ref('shopify_order_shipping_line_data') }}"
    order_shipping_tax_line_source: "{{ ref('shopify_order_shipping_tax_line_data') }}"
    order_tag_source: "{{ ref('shopify_order_tag_data') }}"
    order_url_tag_source: "{{ ref('shopify_order_url_tag_data') }}"
    price_rule_source: "{{ ref('shopify_price_rule_data') }}"
    product_image_source: "{{ ref('shopify_product_image_data') }}"
    product_tag_source: "{{ ref('shopify_product_tag_data') }}"
    shop_source: "{{ ref('shopify_shop_data') }}"
    tender_transaction_source: "{{ ref('shopify_tender_transaction_data') }}"
    abandoned_checkout_discount_code_source: "{{ ref('shopify_abandoned_checkout_discount_code_data') }}"
    order_discount_code_source: "{{ ref('shopify_order_discount_code_data') }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  shopify_source_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    shopify_customer_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        default_address_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        processed_at: timestamp
        cancelled_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        customer_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_data:
      +column_types:
        _fivetran_synced: timestamp
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        variant_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_refund_data:
      +column_types:
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_line_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        published_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_adjustment_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_variant_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        inventory_item_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_transaction_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_refund_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_abandoned_checkout_discount_code_data:
      +column_types:
        amount: float
    shopify_abandoned_checkout_data:
      +column_types:
        total_line_items_price: float
        billing_address_phone: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        shipping_address_phone: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shopify_discount_code_data:
      +column_types:
        usage_count: float
    shopify_order_discount_code_data:
      +column_types:
        amount: float
    shopify_order_shipping_tax_line_data:
      +column_types:
        price: float
    shopify_order_shipping_line_data:
      +column_types:
        discounted_price: float
        price: float
    shopify_price_rule_data:
      +column_types:
        prerequisite_subtotal_range: float
        value: float
    shopify_collection_data:
      +column_types:
        disjunctive: boolean
    shopify_metafield_data:
      +column_types:
        value_type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shopify_shop_data:
      +column_types:
        taxes_included: boolean
        google_apps_login_enabled: boolean
        county_taxes: boolean